=== ra3xdh/qucs_s/library/components/Component.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Component">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="Description"/>
        <xs:element name="Models">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="DefaultModel">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="value"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="SpiceModel">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="value"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Netlists">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="QucsatorNetlist" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Include" maxOccurs="1" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="value"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="value"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="NgspiceNetlist" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Include" maxOccurs="1" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="value"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="value"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="CDLNetlist" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Include" maxOccurs="1" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="value"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="value"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="XyceNetlist" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Include" maxOccurs="1" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="value"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="value"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Symbols">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Symbol">
                <xs:complexType>
                  <xs:choice maxOccurs="unbounded" minOccurs="0">
                    <xs:element name="PortSym">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:int" name="x"/>
                            <xs:attribute type="xs:int" name="y"/>
                            <xs:attribute type="xs:byte" name="type"/>
                            <xs:attribute type="xs:short" name="angle"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Line" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:int" name="x1"/>
                            <xs:attribute type="xs:int" name="y1"/>
                            <xs:attribute type="xs:int" name="x2"/>
                            <xs:attribute type="xs:int" name="y2"/>
                            <xs:attribute type="xs:string" name="color" use="optional"/>
                            <xs:attribute type="xs:int" name="width" use="optional"/>
                            <xs:attribute type="xs:byte" name="style" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Arc" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:int" name="x"/>
                            <xs:attribute type="xs:int" name="y"/>
                            <xs:attribute type="xs:int" name="arcWidth"/>
                            <xs:attribute type="xs:int" name="height"/>
                            <xs:attribute type="xs:int" name="angle"/>
                            <xs:attribute type="xs:int" name="len"/>
                            <xs:attribute type="xs:string" name="color" use="optional"/>
                            <xs:attribute type="xs:int" name="width" use="optional" default="2"/>
                            <xs:attribute type="xs:byte" name="style" use="optional" default="1"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:choice>
                  <xs:attribute type="xs:string" name="id"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Parameters">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Parameter" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Description"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="name"/>
                  <xs:attribute type="xs:string" name="unit"/>
                  <xs:attribute type="xs:string" name="default_value"/>
                  <xs:attribute type="xs:boolean" name="show"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:string" name="library"/>
      <xs:attribute type="xs:string" name="name"/>
      <xs:attribute type="xs:string" name="schematic_id"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ra3xdh/qucs_s/library/components/Cmim.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 131 BiCmos components" name="Cmim" schematic_id = "C">
    <Description>
        SG13G2 MiM capacitor
    </Description>
    <Models>
            <DefaultModel value="cmim">
            </DefaultModel>
            <SpiceModel value="cmim">
            </SpiceModel>
    </Models>
    <Netlists>
            <NgspiceNetlist value ="">
                    <Include value="">
                    </Include>
            </NgspiceNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
            <PortSym x="-30" y="0" type="1" angle="0" />
            <Line x1="-4" y1="-11" x2="-4" y2="11" color="#000080" width="2" style="1" />
            <Line x1="4" y1="-11" x2="4" y2="11" color="#000080" width="2" style="1" />
            <Line x1="-30" y1="0" x2="-4" y2="0" color="#000080" width="2" style="1" />
            <Line x1="4" y1="0" x2="30" y2="0" color="#000080" width="2" style="1" />
            <PortSym x="30" y="0" type="2" angle="127"/>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="w" unit="um" default_value="10.0" show="true">
            <Description>Width</Description>
        </Parameter>
        <Parameter name="l" unit="um" default_value="10.0" show="true">
            <Description>Length</Description>
        </Parameter>
        <Parameter name="m" unit="" default_value="1" show="true">
            <Description>multiplier</Description>
        </Parameter>
    </Parameters>
</Component>

=== ra3xdh/qucs_s/library/components/Rsil.xml
<?xml version="1.0"?>
<Component
  xsi:noNamespaceSchemaLocation="Component.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  library="IHP 131 BiCmos components" name="Rsil" schematic_id = "Rsil">
    <Description>
        SG13G2 Salicide resistor
    </Description>
    <Models>
        <DefaultModel value="Rsil">
        </DefaultModel>
        <SpiceModel value="Rsil">
        </SpiceModel>
    </Models>
    <Netlists>
        <NgspiceNetlist value = 'Xrsil{PartCounter} {nets} rsil w={w} l={l} m={m}'>
            <Include value=".LIB {PDK_ROOT}/ihp-sg13g2/libs.tech/ngspice/models/cornerRES.lib res_typ">
            </Include>
        </NgspiceNetlist>
        <CDLNetlist value = 'R{PartCounter} {nets} rsil w={w} l={l} m={m}'> </CDLNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
           <File>{QUCS_S_COMPONENTS_LIBRARY}/Resistor.sym</File>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="w" unit="um" default_value="0.5" show="true">
            <Description>Width</Description>
        </Parameter>
        <Parameter name="l" unit="um" default_value="0.5" show="true">
            <Description>Length</Description>
        </Parameter>
        <Parameter name="m" unit="" default_value="1" show="true">
            <Description>multiplier</Description>
        </Parameter>
        <Parameter name="b" unit="" default_value="0" show="true">
            <Description>Number of bends</Description>
        </Parameter>
    </Parameters>
</Component>

=== ra3xdh/qucs_s/library/components/ACPowerSource.xml
<?xml version="1.0"?>
<Component
    xsi:noNamespaceSchemaLocation="Component.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    library="IHP 131 BiCmos components" name="AC Power Source" schematic_id = "Pac">
    <Description>
        AC Power Source
    </Description>
    <Models>
        <DefaultModel value="Pac">
        </DefaultModel>
        <SpiceModel value="VP">
        </SpiceModel>
    </Models>
    <Netlists>
            <QucsatorNetlist value = 'Pac:P{PartCounter} {nets} Num="{PartCounter}" Z="{Z}" P="{P}" f="{f}" Temp="{Temp}"'>
            </QucsatorNetlist>
            <NgspiceNetlist value = 'VP{PartCounter} {nets} dc 0 ac {P} SIN(0 {P} {f}) portnum {NumPorts} z0 {Z}'>
            </NgspiceNetlist>
    </Netlists>
    <Symbols>
        <Symbol id="Standard">
            <PortSym x="0" y="30" type="1" angle="270" />
            <Line x1="11" y1="-22" x2="11" y2="22" color="#35322F" width="0" style="1" /> <!-- Outer box -->
            <Line x1="-11" y1="-22" x2="-11" y2="22" color="#35322F" width="0" style="1" />
            <Line x1="11" y1="-22" x2="-11" y2="-22" color="#35322F" width="0" style="1" />
            <Line x1="11" y1="22" x2="-11" y2="22" color="#35322F" width="0" style="1" />
            <Line x1="0" y1="30" x2="0" y2="19" color="#000080" width="2" style="1" />
            <Line x1="0" y1="-30" x2="0" y2="-19" color="#000080" width="2" style="1" />
            <Line x1="0" y1="1" x2="0" y2="-3" color="#000080" width="2" style="1" />
            <Line x1="5" y1="-3" x2="5" y2="-19" color="#000080" width="2" style="1" />
            <Line x1="-5" y1="-3" x2="-5" y2="-19" color="#000080" width="2" style="1" />
            <Line x1="5" y1="-3" x2="-5" y2="-3" color="#000080" width="2" style="1" />
            <Line x1="5" y1="-19" x2="-5" y2="-19" color="#000080" width="2" style="1" />
            <Arc x="-9" y="1" arcWidth="18" height="18" angle="0" len="5760" color="#000080" width="2" /> <!-- Circle -->
            <Arc x="-6" y="6" arcWidth="6" height="6" angle="0" len="2880" color="#000080" width="2" /> <!-- Half sine -->
            <Arc x="0" y="6" arcWidth="6" height="6" angle="2880" len="2880" color="#000080" width="2" /> <!-- The other half of the sine -->
            <Line x1="-5" y1="-25" x2="-11" y2="-25" color="#FF0000" width="1" style="1" /> <!-- Plus sign -->
            <Line x1="-8" y1="-28" x2="-8" y2="-22" color="#FF0000" width="1" style="1" />
            <Line x1="-5" y1="25" x2="-11" y2="25" color="#000000" width="1" style="1" /> <!-- Minus sign -->
            <PortSym x="0" y="-30" type="2" angle="90"/>
        </Symbol>
    </Symbols>
    <Parameters>
        <Parameter name="NumPorts" unit="" default_value="1" show="true">
            <Description>Number of the port</Description>
        </Parameter>
        <Parameter name="Z" unit="Ohm" default_value="50" show="true">
            <Description>Port impedance</Description>
        </Parameter>
        <Parameter name="P" unit="dBm" default_value="0" show="true">
            <Description>(Available) AC power (dBm)</Description>
        </Parameter>
        <Parameter name="Vrms" unit="V" default_value="sqrt(Z/1000.0)*10^(P/20)" show="true">
            <Description>RMS Voltage</Description>
        </Parameter>
        <Parameter name="Vpp" unit="V" default_value="2.0*Vrms*sqrt(2.0)" show="false">
            <Description>Peak-to-Peak Voltage</Description>
        </Parameter>
        <Parameter name="f" unit="GHz" default_value="1" show="true">
            <Description>Frequency</Description>
        </Parameter>
        <Parameter name="Temp" unit="" default_value="26.85" show="false">
            <Description>Simulation temperature (C)</Description>
        </Parameter>
    </Parameters>
</Component>
